### ISSUE TITLE
Question: What is the "ROI" tab in the module config page?

### ISSUE THREAD

**Issue by work67** [mailjet/prestashop-mailjet-plugin-apiv3#100]
Hi, 

see the screenshot:

![s224](https://user-images.githubusercontent.com/9611556/101984084-ce0ad500-3c87-11eb-8426-b054c2ceaa35.png)

What is this tab about?

**Comment by work67** [comment]
When/how will be filled with data?

**Comment by oleksandr-mykhailenko** [comment]
Probably this will help to you - https://www.mailjet.com/blog/email-best-practices/email-marketing-roi/
