### ISSUE TITLE
Error 500 at the install - Prestashop 1.7.7.0 - Unable to load template setup_landing.tpl

### ISSUE THREAD

**Issue by btronquo** [mailjet/prestashop-mailjet-plugin-apiv3#102]
Hello (ou bonjour)

I have an 500 when I install the plugin for the first time with the last Prestashop update, 1.7.7.0
I don't have any other plugins exept a template with its self plugins

Could you help me to resolve this?

Many thanks

The error in question:
```
CRITICAL19:00:25 | php | Uncaught Exception: Unable to load template 'file:/views/templates/admin/setup_landing.tpl' in '/home/clients/51b80e2ba128921bcdd3f0f45eb9f09e/sites/bankanglestudio.com/modules/mailjet/views/templates/admin/configuration.tpl'
-- | -- | --
CRITICAL19:00:25 | request | Uncaught PHP Exception SmartyException: "Unable to load template 'file:/views/templates/admin/setup_landing.tpl' in '/home/clients/51b80e2ba128921bcdd3f0f45eb9f09e/sites/bankanglestudio.com/modules/mailjet/views/templates/admin/configuration.tpl'" at /home/clients/51b80e2ba128921bcdd3f0f45eb9f09e/sites/bankanglestudio.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php line 195
```

**Comment by ibragims** [comment]
open file: \modules\mailjet\views\templates\admin\configuration.tpl

find: {include file="**$MJ_local_path/views/templates/admin/**$MJ_template_name.tpl"}
replace with: {include file="**./**$MJ_template_name.tpl"}

**Comment by btronquo** [comment]
Perfect @ibragims , Thanks a lot :) 
It works very well
