### ISSUE TITLE
spam subscription

### ISSUE THREAD

**Issue by Ditwo** [mailjet/prestashop-mailjet-plugin-apiv3#103]
Hello,

The context is Prestashop 1.7.6.5, module mailjet 3.4.20, module ps_emailsubscription 2.6.0 with email verification option. Country web site Belgium.

I noticed 1300 subscriptions into the PrestaShop Customers Master List of Mailjet for the last 30 days and it seems to be spam subscriptions.

- In the ps_emailsubscription table, the ip is 188.191.21.7 (Ukraine) for all these 1300 subscriptions.
- In the customer table, no data. they are not customers, only subscribers.
- there is no synchronization between the Prestashop Mailjet module and Mailjet regarding the subscribers

SO why all these subscriptions in Mailjet ?

Here are some weird details :
At the time of the registration there is one line in acces log, which is :
188.191.21.7 - - [24/Dec/2020:12:40:46 +0100] "POST /fr/ HTTP/1.1" 200 32343 "-" "**python-requests/2.24.0**"
No line related to ps_emailsubscription, on the contrary of actual / regular subscription, which looks like to :
ipXXXX - -  [24/Dec/2020:10:40:06 +0100] "POST /fr/module/ps_emailsubscription/subscription HTTP/1.1" 200

Do you think hackers have found out a way to subscribe via Prestashop to the Mailjet list?

Many thans in advance for your highlights, best regards
Denis

**Comment by oleksandr-mykhailenko** [comment]
Hello, in theory it could be possible. When they know your html on the website, they could create such script
