### ISSUE TITLE
Fix for connect and config problem

### ISSUE THREAD

**Issue by ibragims** [mailjet/prestashop-mailjet-plugin-apiv3#104]
If someone has problem to Connect/config the plugin.

Edit mailjet.php

**find line 1387 - 1398**
$this->context->smarty->assign(array(
'MJ_templates' => $this->mj_template->getTemplates(),
'MJ_iframes' => $this->mj_template->getIframesURL(),
'MJ_errors' => $this->errors_list,
'MJ_page_name' => $this->page_name,
'MJ_template_name' => $this->mj_pages->getTemplateName($this->page_name),
'MJ_template_tab_name' => $this->mj_pages->getTemplateTabName($this->page_name),
'MJ_authentication' => $this->isAccountSet(),
'MJ_TOKEN_USER' => isset($this->account->{'TOKEN_' . $this->context->employee->id}) ?
$this->account->{'TOKEN_' . $this->context->employee->id} : null,
'MJ_user_plan' => $this->getPlan(),
));

**and replace with**
$this->context->smarty->assign(
array(
'MJ_templates' => $this->mj_template->getTemplates(),
'MJ_iframes' => $this->mj_template->getIframesURL(),
'MJ_errors' => $this->errors_list,
'MJ_page_name' => $this->page_name,
'MJ_template_name' => $this->mj_pages->getTemplateName($this->page_name),
'MJ_template_tab_name' => $this->mj_pages->getTemplateTabName($this->page_name),
'MJ_authentication' => $this->isAccountSet(),
'MJ_TOKEN_USER' => isset($this->account->{'TOKEN_' . $this->context->employee->id}) ? $this->account->{'TOKEN_' . $this->context->employee->id} : null,
'MJ_user_plan' => $this->getPlan(),
'MJ_base_dir' => $this->module_access['uri'],
'MJ_local_path' => $this->module_access['dir'],
'MJ_REQUEST_PAGE_TYPE' => MailJetPages::REQUEST_PAGE_TYPE,
'MJ_ADMINMODULES_TOKEN' => Tools::getAdminTokenLite('AdminModules'),
'MJ_available_pages' => $smarty_page,
'MJ_tab_page' => $this->mj_pages->getPages(MailJetPages::REQUIRE_PAGE),
'MJ_adminmodules_link' => $this->getAdminModuleLink(array()),
'MJ_allemails_active' => Configuration::get('MJ_ALLEMAILS'),
'MJ_TOKEN' => $this->account->TOKEN,
'nobug' => $nobug,
'mjSenders' => $this->getOnlyEmailSenders($mjSenders),
'currentSender' => $currentSender
)
);

**Comment by btronquo** [comment]
Perfect, this is the right way to setup mailjet.

I don't see any update from the mailjet team on this repo, does this mean it's abandoned ?

**Comment by oleksandr-mykhailenko** [comment]
Hello, it's not abandoned. Sorry to hear, that you have problems with that. We are working on plugin and soon we will release a new version with fixes for bugs

**Comment by oleksandr-mykhailenko** [comment]
Issues was fixed and deployed into master branch
