### ISSUE TITLE
Prestashop 1.7.7

### ISSUE THREAD

**Issue by forever80-dev** [mailjet/prestashop-mailjet-plugin-apiv3#105]
hello 

My version prestashop is 1.7.7 and this return error on chargement this packet

Regards

**Comment by destockinfo** [comment]
I have the same issue, module is not compatible with Prestashop 1.7.7.X
This is a big problem...
I can't use Mailjet now (it was working fine on 1.7.6.9)

**Comment by forever80-dev** [comment]
Ok so I set it up differently, using mailjet's SMTP it works fine.

**Comment by garri-dev** [comment]
Same problem here...

**Comment by oleksandr-mykhailenko** [comment]
Hello, thank you for notice that. We are working on that

**Comment by oleksandr-mykhailenko** [comment]
Issues was resolved by another changes
