### ISSUE TITLE
Error after install on Prestashop 1.7.7.2

### ISSUE THREAD

**Issue by copostic** [mailjet/prestashop-mailjet-plugin-apiv3#106]
Hello,

I have this error when I try to access to the configuration page of the v3.4.20:
![image](https://user-images.githubusercontent.com/17200174/109521300-74a78a80-7aad-11eb-91a0-c310561c77e7.png)

I checked for permissions but they're set to 775 on directories and 664 on files. 
Do you have any solution or an idea of something I could've made wrong ?

**Comment by garri-dev** [comment]
Same problem here...

**Comment by DelecroixQuentin** [comment]
Quick fix for you:
Add the following line in this [array](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/blob/master/mailjet.php#L1387-L1398)
`'MJ_local_path' => $this->module_access['dir'],`

**Comment by alice-elix** [comment]
> 
> 
> Quick fix for you:
> Add the following line in this [array](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/blob/master/mailjet.php#L1387-L1398)
> `'MJ_local_path' => $this->module_access['dir'],`

I think there has been an update, because in the array there is already this line, but the problem is still there

**Comment by JimmyBWY** [comment]
> Quick fix for you:
> Add the following line in this [array](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/blob/master/mailjet.php#L1387-L1398)
> `'MJ_local_path' => $this->module_access['dir'],`

Nice works fine

**Comment by micka-fdz** [comment]
Hi. Please add this fix to next release.

**Comment by MJBGO** [comment]
Same problem here. Please provide a fix :(

**Comment by oleksandr-mykhailenko** [comment]
Hello, We are doing a review of current version and will check. How it works right now and do customers have a problems with that path. Thank you

**Comment by oleksandr-mykhailenko** [comment]
This was fixed in previous releases
