### ISSUE TITLE
Please release the latest development version

### ISSUE THREAD

**Issue by MJBGO** [mailjet/prestashop-mailjet-plugin-apiv3#113]
Hello,

Can you plan a release of the development branch to fixes all issues with PS 1.7.7 and 1.7.8 ?
I was doing a PR to fix the missing "MJ_local_path" key in mailjet.php but I saw it was fixed in this branch.

This is related to :
- https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/issues/102
- https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/issues/105
- https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/issues/106

Thanks

**Comment by oleksandr-mykhailenko** [comment]
Hello @MJBGO Was the issue fixed and what do you suggest to release in the new version ?
