### ISSUE TITLE
Connection issue (Prestashop 1.7.7.5)

### ISSUE THREAD

**Issue by Weeby75** [mailjet/prestashop-mailjet-plugin-apiv3#115]
Hello, 
We have downloaded the version 3.4.20 and 3.4.21 of Mailjet on our Prestashop 1.7.7.5 but we have a problem with the connection. Indeed when I click on the "connection" button I am directly sent to the Home of Prestashop. 
Do you also encounter this problem? https://www.loom.com/share/e1379b3af43f4a4f8036a58d43267740
Thanks in advance,

**Comment by laurent-triptic** [comment]
hello, I've got the same issue with my 1.7.7.2 Prestashop version.
Is there any quickfix to use ?
Thanks

**Comment by oleksandr-mykhailenko** [comment]
Hello @Weeby75 @laurent-triptic  Is it still a problem ? Could post more details please, maybe about replications steps

**Comment by oleksandr-mykhailenko** [comment]
Close issue. The problem was fixed
