### ISSUE TITLE
getTabLink Symfony exception

### ISSUE THREAD

**Issue by dutty5** [mailjet/prestashop-mailjet-plugin-apiv3#116]
There is no getTabLink function in classes/Link.php prior to all PS releases before 18 Jul 2019, including v1.7.5.x and earlier.
This function was added to Prestashop on 18 Jul 2019 (commit https://github.com/PrestaShop/PrestaShop/commit/5e87c9b9dadc198a33684b2dc60416f89f13eea3).

So, your use of this function introduced on 9 Dec 2021 (in commit https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/commit/7792952f12fcb8f5976eedb57d22981b0c8bd21f) leads to Symfony exception in latest release v3.4.21 making this version unusable in Prestashop v1.7.5.x and earlier.

Please fix. Thank you.

**Comment by chtipepere** [comment]
Any news on this issue ?

**Comment by vcopleutre** [comment]
For PS 1.6, you can easily change
`$link = $this->context->link->getTabLink($tab)`
By
`$this->context->link->getAdminLink('AdminModules')`

A commit could include a version check and use getTabLink or getAdminLink. 

Note : no issue about $tab, used only with the getTabLink method

Have a nice day

**Comment by enigmoes** [comment]
Hello,

I have the same problem and I have solved it with this code in the "mailjet.php" file.

$tab = ['class_name' => 'AdminModules'];
          if (version_compare(_PS_VERSION_, '1.7.8.0', '>=')) {
              $link = $this->context->link->getTabLink($tab) . '&set=' . $this->name . '&conf=4&token=' . Tools::getAdminTokenLite('AdminModules') . '&sync_list=true';
          } plus {
              $link = $this->context->link->getAdminLink($tab['class_name']) . '&set=' . $this->name . '&conf=4&token=' . Tools::getAdminTokenLite('AdminModules') . '&sync_list=true';
          }

I hope the developers will add this in future updates, it is required for compatibility with previous versions of Prestashop.

Cheers

**Comment by oleksandr-mykhailenko** [comment]
Hello
Thank you all for participating in this. PR was merged and issue was fixed
