### ISSUE TITLE
trans() method not valid ps 1.6

### ISSUE THREAD

**Issue by vcopleutre** [mailjet/prestashop-mailjet-plugin-apiv3#119]
File : mailjet.php
Line : 1515

Incriminated code : ` 'title' => $this->trans('Settings', [], 'Admin.Global'),`

Issue : the module is not 1.6 compliant due to this code.

Thanks for fixing it

**Comment by Sekar33000** [comment]
Hello, same here,  can't install in prestashop  1.6 

[PrestaShop] Fatal error in module file : /modules/mailjet/mailjet.php:
Uncaught Error: Call to undefined method Link::getTabLink() in /modules/mailjet/mailjet.php:1476 Stack trace: #0 /controllers/admin/AdminModulesController.php(868): Mailjet->getContent() #1 /controllers/admin/AdminModulesController.php(1117): AdminModulesControllerCore->postProcessCallback() #2 /classes/controller/Controller.php(178): AdminModulesControllerCore->postProcess() #3 /classes/Dispatcher.php(367): ControllerCore->run() #4 /override/classes/Dispatcher.php(22): DispatcherCore->dispatch() #5 admin/index.php(58): Dispatcher->dispatch() #6 {main} thrown

**Comment by vcopleutre** [comment]
Hi @Sekar33000 
See my answer : https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/issues/116#issuecomment-1057800957

Have a nice day

**Comment by Sekar33000** [comment]
Thanks!

**Comment by oleksandr-mykhailenko** [comment]
Hello @vcopleutre you fixes was merged in scope of attached PR. Thank you for helping
