### ISSUE TITLE
The file doesn't seem to be a valid module .zip file.

### ISSUE THREAD

**Issue by Laura78550** [mailjet/prestashop-mailjet-plugin-apiv3#123]
Hello,
Sorry but I'm trying to download the latest version of your module and I have an error while downloading Prestashop version 1.7.6.1.
Prestashop tells me that the file doesn't seem to be a valid module .zip file.
I have downloaded the source code from https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/releases/tag/v3.5.0.
Can you help me to understand why?

**Comment by aabarca-gi** [comment]
Hello,

Same issue I'm on  1.7.6.1 as well. 
I Tried older version, and I have the same problem.

Thanks.

**Comment by oleksandr-mykhailenko** [comment]
Hello @Laura78550 @aabarca-gi 
for installation you should rename archive and folder in it to name `mailjet`. We already have this item in the readme.
