### ISSUE TITLE
Unsub still in prestashop

### ISSUE THREAD

**Issue by AaronTajriba** [mailjet/prestashop-mailjet-plugin-apiv3#135]
When an customer unsubscribes, the email is still in the PrestaShop newsletter signup module. while in mailjet the address is flagged as unsubscribed. How could an user resubscribe?

**Comment by tajriba** [comment]
@oleksandr-mykhaileno how to fix this? There is now ping back to prestashop when users unsubscribes from mailjet contact list to prestashop. so users still subscribed in the prestashop environment.

**Comment by oleksandr-mykhailenko** [comment]
Fix was made
