### ISSUE TITLE
PHP 8 Compatibility - Warnings Regarding Incorrect PHP Data Types and Session Start in Mailjet.Overlay.class.php and FrontController.php

### ISSUE THREAD

**Issue by maitmansour** [mailjet/prestashop-mailjet-plugin-apiv3#137]
**Issue Type:** Bug

**Environment:** 
[Prestashop 8.0 - Php 8.1]

**Issue Description:**
While running the application, I encountered the following PHP warnings:

1. "integer" will be interpreted as a class name. Did you mean "int"? Write "\integer" to suppress this warning in /home/xxx/public_html/modules/mailjet/libraries/Mailjet.Overlay.class.php on line 928

2. "boolean" will be interpreted as a class name. Did you mean "bool"? Write "\boolean" to suppress this warning in /home/xxx/public_html/modules/mailjet/libraries/Mailjet.Overlay.class.php on line 978

3. "integer" will be interpreted as a class name. Did you mean "int"? Write "\integer" to suppress this warning in /home/xxx/public_html/modules/mailjet/libraries/Mailjet.Overlay.class.php on line 5053

The warnings suggest that the terms "integer" and "boolean" will be interpreted as class names, and recommends using "int" and "bool" instead. Additionally, the application attempts to start a session after headers have already been sent.

**Expected Behavior:**
The PHP script should run without issuing warnings related to outdated or misinterpreted terms, and sessions should be started correctly.

**Actual Behavior:**
Currently, the script issues warnings about the use of "integer" and "boolean" instead of "int" and "bool", respectively. Furthermore, there is an issue with session start in FrontController.php.

**Steps to reproduce:**
1. Install the module
2. Go to home page for example

**Possible Solution:**
Update all instances of "integer" to "int" and "boolean" to "bool" in the file Mailjet.Overlay.class.php at the indicated lines (928, 978, 5053.....).

Please let me know if you need any additional information. 

Thanks!

**Comment by oleksandr-mykhailenko** [comment]
Hello @maitmansour 
Thank you
we take this into work and make an update soon

**Comment by oleksandr-mykhailenko** [comment]
We are making a release
Thank you
