### ISSUE TITLE
PrestaShop 8.1.0, PHP 8.2.8 and a problem with entering API keys on

### ISSUE THREAD

**Issue by MartinK111** [mailjet/prestashop-mailjet-plugin-apiv3#140]
Hello,

I have PrestaShop 8.1.0
PHP version: 8.2.8
The version of the module is v3.6.0

I have a problem with the Login Information setting after installing the module.. I enter the correct Api and Secret keys and I get the message "Please verify that you have entered correct API and secret key." I tried it several times.

Here is screenshot:
![mailjet](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/assets/143091362/3abd7dc1-9b26-443c-bc76-2569a22205b1)

Can you please help me?

Thanks.

**Comment by MartinK111** [comment]
Hello,

Thank you for the quick reply. I have PHP 8.2.9, and I did a fresh install of PrestaShop 8.1.0 Regarding your question, unfortunately I can't say for sure if this problem only occurs with PHP 8.1+. I'm a bit inexperienced in these technical details. In addition, the module takes a very long time to respond. When I click on it, I wait 30 seconds for it to load. I suppose it could be a problem with PHP version 8.2+, but I'm not sure.

Thanks for your understanding and help.

**Comment by MartinK111** [comment]
Hello,

Thank you for the quick reply. I have PHP 8.2.9, and I did a fresh install
of PrestaShop 8.1.0 Regarding your question, unfortunately I can't say for
sure if this problem only occurs with PHP 8.1+. I'm a bit inexperienced in
these technical details. In addition, the module takes a very long time to
respond. When I click on it, I wait 30 seconds for it to load. I suppose it
could be a problem with PHP version 8.2+, but I'm not sure.

Thanks for your understanding and help.

pi 25. 8. 2023 o 18:00 Oleksandr Mykhailenko ***@***.***>
napísal(a):

**Comment by oleksandr-mykhailenko** [comment]
Thank you @MartinK111 
Plugin was not tested with 8.2+ version, so it could be situations that we are not aware. Anyway, It's a new challenge for us. We take this into work

**Comment by oleksandr-mykhailenko** [comment]
Fixed
