### ISSUE TITLE
Installation of module mailjet failed. The module is invalid and cannot be loaded.

### ISSUE THREAD

**Issue by siomosp** [mailjet/prestashop-mailjet-plugin-apiv3#145]
Hello!
Prestahop 1.7.5.2
Installation of module mailjet failed. The module is invalid and cannot be loaded.
Any ideas how to fix it ?

**Comment by oleksandr-mykhailenko** [comment]
Hello @siomosp 
Do you have more information about that ? Logs, errors messages ? Did you go with installation steps ?

**Comment by hipercohete** [comment]
Hi @oleksandr-mykhailenko 
I have an issue loading the module within PS 1.7.8.7.
I download the .zip  , rename both folders and zip again and then try to upload but I get the next message (see pic. attached).

wait for your feedback

thanks
<img width="441" alt="Screenshot 2023-11-20 215157" src="https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/assets/151576894/317c6635-2cce-4aa9-b28c-5a59af7acc00">

**Comment by oleksandr-mykhailenko** [comment]
Hi @hipercohete 
So in this case I can't give you extended answer because I do not have any logs. If you have any server logs with messages, it would be nice to see them. There are too many problems could be in such cases, and it could either plugin problem or your local env problem. Please, give more details here

**Comment by CCyril13** [comment]
Good morning,
I have exactly the same problem as the 2 mentioned above. The module does not want to install. The message is: This file does not appear to be a valid module .zip file.
There is nothing in the logs. My version is prestashop 1.7.6.8
I tried to zip the files but the result is identical.
Thank you in advance for your help.
Cyril
![modul](https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/assets/155448859/03796c39-9ec1-46e2-802d-cc74c1a80209)
