### ISSUE TITLE
Error when creating a campaign in Prestashop

### ISSUE THREAD

**Issue by Philographie** [mailjet/prestashop-mailjet-plugin-apiv3#60]
Hello,

Prestashop [1.7.3.0], prestashop-mailjet-plugin-apiv3 [v3.4.12] and a Mailjet account configured, in french.

I can create a new campaign in Mailjet website : all is working great.
In Prestashop > Mailjet configuration, when I want to create a new campaign, I have the notification «Une erreur inattendue s'est produite. Merci de réessayer.» when I select one of the 2 tools editor and click «Save and continue».

Has anyone ever encountered this issue ?

Thanks,
françois

**Comment by Philographie** [comment]
Hi,
No one arround ? ;-)

françois

**Comment by mskochev** [comment]
Hello François,

Please try to install this older version. It excludes the ROI stats feature of the plugin which causes the issue that you experience for some users.
https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/releases/tag/3.4.8.5

Best regards,
Mailjet Plugins Team

**Comment by RedbeaR-FR** [comment]
Same problem and the 3.4.9 works for me ;) thanks @mskochev
