### ISSUE TITLE
Error: Call to a member function getTemplateName() on null

### ISSUE THREAD

**Issue by Klemart3D** [mailjet/prestashop-mailjet-plugin-apiv3#89]
Hi,
I just installed your plugin v3.4.18, but when I'm trying to access your config page, I get the following:
```
[PrestaShop] Fatal error in module file: /vagrant/httpdocs/modules/mailjet/mailjet.php:1395
Call to a member function getTemplateName() on null
```

![mailjet-error](https://user-images.githubusercontent.com/7419525/56808506-f71bef00-6831-11e9-974b-5b93157bdc03.png)

Do you know why?

**Comment by mskochev** [comment]
Hi, we are checking what could be causing the issue

**Comment by mskochev** [comment]
Hi @Klemart3D, please can you download the fixed version from this branch:
https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/tree/development
Let me know if it solves the problem.

**Comment by LupusVII** [comment]
Hello @mskochev,
I had the same issue and your answer fixed it ;)
Thanks !

**Comment by Klemart3D** [comment]
I approve, problem is now solved, thank you!
