### ISSUE TITLE
MYSQL error with Segments

### ISSUE THREAD

**Issue by alizeegtd** [mailjet/prestashop-mailjet-plugin-apiv3#96]
I created 2 segments in the Mailjet module:
- customers who have at least 1 order and bought one specific product (id = 4)
- customers who have at least 1 order and not bought one specific product (id = 4)

When I change the status of an order, I get this error:
![Capture d’écran 2019-08-21 à 15 07 23](https://user-images.githubusercontent.com/9107384/63434888-3516d180-c426-11e9-94e2-5eb5b3f8dde6.png)

How can I manage this?

**Comment by mskochev** [comment]
Hello, thanks for reporting this issue. We'll check and come back with a solution.

**Comment by oleksandr-mykhailenko** [comment]
I close issue, due to inactivity
