### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by Daaaaad** [mailjet/prestashop-mailjet-plugin-apiv3#99]
Hello,

When I try to configure the module and set the sender email I get this error message : 

https://www.dropbox.com/s/aq3ton9x3y10zkh/Capture%20d%E2%80%99%C3%A9cran%202020-09-07%20%C3%A0%2013.42.31.png?dl=0

This address is valid : https://www.dropbox.com/s/ze4o1ve3i2thv03/Capture%20d%E2%80%99%C3%A9cran%202020-09-07%20%C3%A0%2013.46.16.png?dl=0

Can you help?

**Comment by Max13** [comment]
You must have added the sender address: https://app.mailjet.com/account/sender

**Comment by adn34** [comment]
I have the same issue, sender address is valid and created (has been for a while) but the module complains about it not being valid. It's even listed under "my account" in the module.

**Comment by alice-elix** [comment]
> 
> 
> I have the same issue, sender address is valid and created (has been for a while) but the module complains about it not being valid. It's even listed under "my account" in the module.

The same here

**Comment by bpuig** [comment]
Same here.

**Comment by oleksandr-mykhailenko** [comment]
Issue was fixed. If you have validated sender it will not complain on it
